const styles = {
  fondo: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 200,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px',
  },
  modal: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    maxWidth: '620px',
    width: '100%',
    maxHeight: '90vh',
    overflowY: 'auto',
    boxShadow: '0 8px 40px rgba(0,0,0,0.18)',
  },
  imagen: {
    width: '100%',
    height: '240px',
    objectFit: 'cover',
    borderRadius: '12px 12px 0 0',
    display: 'block',
  },
  cuerpo: {
    padding: '28px 32px',
  },
  carrera: {
    fontSize: '0.72rem',
    fontWeight: '700',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#ff5117',
    marginBottom: '8px',
    display: 'block',
  },
  titulo: {
    fontSize: '1.3rem',
    fontWeight: '700',
    color: '#111111',
    marginBottom: '16px',
    lineHeight: '1.35',
  },
  bannerFecha: {
    backgroundColor: '#ff5117',
    color: '#ffffff',
    padding: '12px 18px',
    borderRadius: '6px',
    fontSize: '0.88rem',
    fontWeight: '600',
    marginBottom: '10px',
  },
  bannerLugar: {
    backgroundColor: '#f0f0f0',
    color: '#333333',
    padding: '10px 18px',
    borderRadius: '6px',
    fontSize: '0.85rem',
    marginBottom: '20px',
  },
  descripcion: {
    fontSize: '0.88rem',
    color: '#444444',
    lineHeight: '1.75',
    marginBottom: '24px',
  },
  btnCerrar: {
    width: '100%',
    padding: '12px',
    backgroundColor: '#111111',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '0.88rem',
    fontWeight: '700',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
  },
};

export default styles;
