import fondo from '../assets/sede_ulima.jpg';

const styles = {
  container: {
    width: '100vw',
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundImage: `url(${fondo})`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    padding: '24px',
  },
  card: {
    width: '100%',
    maxWidth: '420px',
    backgroundColor: '#ffffff',
    borderRadius: '10px',
    padding: '40px 36px',
    fontFamily: "'Montserrat', sans-serif",
    boxShadow: '0 10px 40px rgba(0,0,0,0.22)',
  },
  logo: {
    width: '52px',
    display: 'block',
    margin: '0 auto 20px auto',
  },
  titulo: {
    fontSize: '1.45rem',
    fontWeight: '700',
    color: '#111111',
    textAlign: 'center',
    marginBottom: '28px',
    lineHeight: '1.3',
  },
  grupo: {
    marginBottom: '18px',
  },
  label: {
    display: 'block',
    fontWeight: '600',
    color: '#444444',
    fontSize: '0.88rem',
    marginBottom: '6px',
  },
  input: {
    width: '100%',
    padding: '12px 14px',
    borderRadius: '6px',
    border: '1px solid #dcdcdc',
    fontSize: '0.95rem',
    fontFamily: "'Montserrat', sans-serif",
    outline: 'none',
    boxSizing: 'border-box',
  },
  inputError: {
    border: '1px solid #cc2200',
  },
  passwordWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  inputPassword: {
    width: '100%',
    padding: '12px 44px 12px 14px',
    borderRadius: '6px',
    border: '1px solid #dcdcdc',
    fontSize: '0.95rem',
    fontFamily: "'Montserrat', sans-serif",
    outline: 'none',
    boxSizing: 'border-box',
  },
  btnOjo: {
    position: 'absolute',
    right: '12px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px',
    color: '#999999',
    display: 'flex',
    alignItems: 'center',
  },
  mensajeError: {
    backgroundColor: '#fff0ed',
    color: '#cc2200',
    border: '1px solid #ffccc4',
    borderRadius: '6px',
    padding: '10px 14px',
    fontSize: '0.83rem',
    marginBottom: '14px',
    fontWeight: '500',
  },
  boton: {
    width: '100%',
    padding: '13px',
    backgroundColor: '#ff5117',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '1rem',
    fontWeight: '700',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
    marginTop: '6px',
  },
  separador: {
    border: 'none',
    borderTop: '1px solid #eeeeee',
    margin: '22px 0 16px 0',
  },
  textoRegistro: {
    textAlign: 'center',
    fontSize: '0.88rem',
    color: '#666666',
  },
  linkRegistro: {
    color: '#ff5117',
    fontWeight: '700',
    textDecoration: 'none',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    fontSize: '0.88rem',
    fontFamily: "'Montserrat', sans-serif",
    padding: 0,
  },
};

export default styles;
