const styles = {
  fondo: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 300,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px',
  },
  modal: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    maxWidth: '460px',
    width: '100%',
    maxHeight: '90vh',
    overflowY: 'auto',
    boxShadow: '0 8px 40px rgba(0,0,0,0.18)',
    fontFamily: "'Montserrat', sans-serif",
  },
  cabecera: {
    padding: '20px 24px 14px',
    borderBottom: '2px solid #ff5117',
  },
  titulo: {
    fontSize: '1.1rem',
    fontWeight: '700',
    color: '#111111',
  },
  cuerpo: {
    padding: '22px 24px',
  },
  footer: {
    padding: '14px 24px',
    borderTop: '1px solid #eeeeee',
    display: 'flex',
    gap: '10px',
    justifyContent: 'flex-end',
  },
  grupo: {
    marginBottom: '14px',
  },
  label: {
    display: 'block',
    fontWeight: '600',
    fontSize: '0.84rem',
    color: '#444444',
    marginBottom: '5px',
  },
  labelAyuda: {
    fontWeight: '400',
    color: '#aaaaaa',
    fontSize: '0.78rem',
  },
  input: {
    width: '100%',
    padding: '10px 13px',
    borderRadius: '6px',
    border: '1px solid #dcdcdc',
    fontSize: '0.9rem',
    fontFamily: "'Montserrat', sans-serif",
    outline: 'none',
    boxSizing: 'border-box',
  },
  inputError: {
    border: '1px solid #cc2200',
  },
  select: {
    width: '100%',
    padding: '10px 13px',
    borderRadius: '6px',
    border: '1px solid #dcdcdc',
    fontSize: '0.9rem',
    fontFamily: "'Montserrat', sans-serif",
    outline: 'none',
    backgroundColor: '#ffffff',
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  passwordWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  inputPassword: {
    width: '100%',
    padding: '10px 38px 10px 13px',
    borderRadius: '6px',
    border: '1px solid #dcdcdc',
    fontSize: '0.9rem',
    fontFamily: "'Montserrat', sans-serif",
    outline: 'none',
    boxSizing: 'border-box',
  },
  btnOjo: {
    position: 'absolute',
    right: '10px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#999999',
    display: 'flex',
    alignItems: 'center',
    padding: '4px',
  },
  mensajeError: {
    color: '#cc2200',
    fontSize: '0.77rem',
    marginTop: '3px',
    fontWeight: '500',
  },
  exito: {
    backgroundColor: '#e8f5e9',
    color: '#2e7d32',
    border: '1px solid #a5d6a7',
    borderRadius: '6px',
    padding: '10px 14px',
    textAlign: 'center',
    fontSize: '0.88rem',
    fontWeight: '600',
    marginBottom: '14px',
  },
  btnCancelar: {
    padding: '10px 20px',
    background: '#f0f0f0',
    color: '#333333',
    border: '1px solid #dcdcdc',
    borderRadius: '6px',
    fontSize: '0.87rem',
    fontWeight: '600',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
  },
  btnGuardar: {
    padding: '10px 20px',
    background: '#ff5117',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '0.87rem',
    fontWeight: '700',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
  },
};

export default styles;
