import fondo from '../assets/sede_ulima.jpg';

const styles = {
  container: {
    width: '100vw',
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundImage: `url(${fondo})`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    padding: '24px',
  },
  card: {
    width: '100%',
    maxWidth: '480px',
    backgroundColor: '#ffffff',
    borderRadius: '10px',
    padding: '40px 36px',
    fontFamily: "'Montserrat', sans-serif",
    boxShadow: '0 10px 40px rgba(0,0,0,0.22)',
  },
  logo: {
    width: '52px',
    display: 'block',
    margin: '0 auto 20px auto',
  },
  titulo: {
    fontSize: '1.35rem',
    fontWeight: '700',
    color: '#111111',
    textAlign: 'center',
    marginBottom: '26px',
  },
  grupo: {
    marginBottom: '15px',
  },
  dosColumnas: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
    marginBottom: '15px',
  },
  label: {
    display: 'block',
    fontWeight: '600',
    color: '#444444',
    fontSize: '0.85rem',
    marginBottom: '5px',
  },
  input: {
    width: '100%',
    padding: '11px 14px',
    borderRadius: '6px',
    border: '1px solid #dcdcdc',
    fontSize: '0.9rem',
    fontFamily: "'Montserrat', sans-serif",
    outline: 'none',
    boxSizing: 'border-box',
  },
  inputError: {
    border: '1px solid #cc2200',
  },
  select: {
    width: '100%',
    padding: '11px 14px',
    borderRadius: '6px',
    border: '1px solid #dcdcdc',
    fontSize: '0.9rem',
    fontFamily: "'Montserrat', sans-serif",
    outline: 'none',
    backgroundColor: '#ffffff',
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  passwordWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  inputPassword: {
    width: '100%',
    padding: '11px 40px 11px 14px',
    borderRadius: '6px',
    border: '1px solid #dcdcdc',
    fontSize: '0.9rem',
    fontFamily: "'Montserrat', sans-serif",
    outline: 'none',
    boxSizing: 'border-box',
  },
  btnOjo: {
    position: 'absolute',
    right: '10px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px',
    color: '#999999',
    display: 'flex',
    alignItems: 'center',
  },
  mensajeError: {
    color: '#cc2200',
    fontSize: '0.78rem',
    marginTop: '4px',
    fontWeight: '500',
  },
  exito: {
    backgroundColor: '#e8f5e9',
    color: '#2e7d32',
    border: '1px solid #a5d6a7',
    borderRadius: '8px',
    padding: '14px 18px',
    textAlign: 'center',
    fontSize: '0.9rem',
    fontWeight: '600',
    marginBottom: '16px',
  },
  boton: {
    width: '100%',
    padding: '13px',
    backgroundColor: '#ff5117',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '0.95rem',
    fontWeight: '700',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
    marginTop: '8px',
  },
  linkVolver: {
    display: 'block',
    textAlign: 'center',
    marginTop: '18px',
    color: '#666666',
    fontSize: '0.88rem',
    textDecoration: 'none',
  },
  linkNaranja: {
    color: '#ff5117',
    fontWeight: '700',
  },
};

export default styles;
