const styles = {
  nav: {
    backgroundColor: '#111111',
    padding: '0 32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'sticky',
    top: 0,
    zIndex: 100,
    boxShadow: '0 2px 8px rgba(0,0,0,0.25)',
    height: '62px',
    flexWrap: 'wrap',
    gap: '8px',
  },
  izquierda: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    cursor: 'pointer',
  },
  logo: {
    width: '28px',
  },
  titulo: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: '1rem',
    letterSpacing: '0.04em',
  },
  naranja: {
    color: '#ff5117',
  },
  badge: {
    backgroundColor: '#ff5117',
    color: '#ffffff',
    fontSize: '0.6rem',
    fontWeight: '700',
    padding: '3px 8px',
    borderRadius: '3px',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },
  derecha: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  btn: {
    padding: '7px 14px',
    background: 'none',
    color: '#cccccc',
    border: '1px solid #3a3a3a',
    borderRadius: '6px',
    fontSize: '0.78rem',
    fontWeight: '600',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
  },
  btnActivo: {
    backgroundColor: '#ff5117',
    color: '#ffffff',
    border: '1px solid #ff5117',
  },
  btnLogout: {
    padding: '7px 14px',
    background: 'transparent',
    color: '#888888',
    border: '1px solid #2a2a2a',
    borderRadius: '6px',
    fontSize: '0.78rem',
    fontWeight: '600',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
  },
};

export default styles;
