const styles = {
  pagina: {
    fontFamily: "'Montserrat', sans-serif",
    backgroundColor: '#f5f5f5',
    minHeight: '100vh',
  },
  contenido: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '32px 24px',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '14px',
    marginBottom: '28px',
  },
  statCard: {
    backgroundColor: '#ffffff',
    borderRadius: '8px',
    padding: '18px 20px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
  },
  statNumero: {
    fontSize: '2rem',
    fontWeight: '700',
    color: '#ff5117',
    lineHeight: 1,
  },
  statLabel: {
    fontSize: '0.76rem',
    color: '#888888',
    marginTop: '4px',
    fontWeight: '600',
  },
  encabezado: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '22px',
    flexWrap: 'wrap',
    gap: '12px',
  },
  tituloSeccion: {
    fontSize: '1.15rem',
    fontWeight: '700',
    color: '#111111',
    borderLeft: '4px solid #ff5117',
    paddingLeft: '12px',
  },
  barraFiltros: {
    display: 'flex',
    gap: '10px',
    marginBottom: '22px',
    flexWrap: 'wrap',
  },
  filtroWrapper: {
    marginBottom: '22px',
  },
  inputBusqueda: {
    flex: 1,
    minWidth: '200px',
    padding: '10px 14px',
    border: '1px solid #dcdcdc',
    borderRadius: '8px',
    fontSize: '0.88rem',
    fontFamily: "'Montserrat', sans-serif",
    outline: 'none',
    backgroundColor: '#ffffff',
  },
  selectFiltro: {
    padding: '10px 14px',
    border: '1px solid #dcdcdc',
    borderRadius: '8px',
    fontSize: '0.88rem',
    fontFamily: "'Montserrat', sans-serif",
    outline: 'none',
    backgroundColor: '#ffffff',
    cursor: 'pointer',
    minWidth: '200px',
  },
  btnNuevo: {
    padding: '10px 20px',
    backgroundColor: '#ff5117',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '0.87rem',
    fontWeight: '700',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
  },
  btnEditar: {
    padding: '6px 12px',
    backgroundColor: '#111111',
    color: '#ffffff',
    border: 'none',
    borderRadius: '5px',
    fontSize: '0.76rem',
    fontWeight: '600',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
  },
  btnEliminar: {
    padding: '6px 12px',
    backgroundColor: '#fff0ed',
    color: '#cc2200',
    border: '1px solid #ffccc4',
    borderRadius: '5px',
    fontSize: '0.76rem',
    fontWeight: '600',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
  },
  accionesFila: {
    display: 'flex',
    gap: '6px',
  },
  tabla: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: '10px',
    overflow: 'hidden',
    boxShadow: '0 2px 10px rgba(0,0,0,0.06)',
    borderCollapse: 'collapse',
  },
  th: {
    padding: '12px 14px',
    backgroundColor: '#f8f8f8',
    color: '#555555',
    fontWeight: '700',
    fontSize: '0.72rem',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    textAlign: 'left',
    borderBottom: '1px solid #eeeeee',
  },
  td: {
    padding: '12px 14px',
    fontSize: '0.85rem',
    color: '#333333',
    borderBottom: '1px solid #f0f0f0',
    verticalAlign: 'middle',
  },
  tdFecha: {
    padding: '12px 14px',
    fontSize: '0.82rem',
    color: '#333333',
    borderBottom: '1px solid #f0f0f0',
    verticalAlign: 'middle',
  },
  tipoEvento: {
    fontSize: '0.73rem',
    color: '#999999',
    marginTop: '2px',
  },
  imgTabla: {
    width: '54px',
    height: '38px',
    objectFit: 'cover',
    borderRadius: '4px',
  },
  badgeCarrera: {
    display: 'inline-block',
    padding: '3px 9px',
    backgroundColor: '#fff4f0',
    color: '#ff5117',
    borderRadius: '4px',
    fontSize: '0.7rem',
    fontWeight: '700',
  },
  badgeProximo: {
    display: 'inline-block',
    padding: '3px 9px',
    backgroundColor: '#e8f5e9',
    color: '#2e7d32',
    borderRadius: '4px',
    fontSize: '0.7rem',
    fontWeight: '700',
  },
  badgeHistorial: {
    display: 'inline-block',
    padding: '3px 9px',
    backgroundColor: '#f0f0f0',
    color: '#777777',
    borderRadius: '4px',
    fontSize: '0.7rem',
    fontWeight: '700',
  },
  sinResultados: {
    padding: '32px',
    textAlign: 'center',
    color: '#999999',
    fontSize: '0.9rem',
    fontStyle: 'italic',
  },
  filaUsuario: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  avatarUsuario: {
    width: '34px',
    height: '34px',
    borderRadius: '50%',
    backgroundColor: '#ff5117',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '700',
    fontSize: '0.82rem',
    flexShrink: 0,
  },
  nombreUsuario: {
    fontWeight: '600',
    fontSize: '0.87rem',
  },
  contadorUsuarios: {
    fontSize: '0.85rem',
    color: '#888888',
    fontWeight: '600',
  },
  tdCorreo: {
    padding: '12px 14px',
    fontSize: '0.8rem',
    color: '#666666',
    borderBottom: '1px solid #f0f0f0',
    verticalAlign: 'middle',
  },
  toast: {
    position: 'fixed',
    bottom: '28px',
    right: '28px',
    backgroundColor: '#111111',
    color: '#ffffff',
    padding: '12px 22px',
    borderRadius: '8px',
    fontSize: '0.88rem',
    fontWeight: '600',
    fontFamily: "'Montserrat', sans-serif",
    boxShadow: '0 4px 16px rgba(0,0,0,0.22)',
    zIndex: 999,
  },
};

export default styles;
