const styles = {
  fondo: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 300,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
  },
  modal: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    maxWidth: '580px',
    width: '100%',
    maxHeight: '90vh',
    overflowY: 'auto',
    boxShadow: '0 8px 40px rgba(0,0,0,0.18)',
    fontFamily: "'Montserrat', sans-serif",
  },
  cabecera: {
    padding: '20px 24px 14px',
    borderBottom: '2px solid #ff5117',
    position: 'sticky',
    top: 0,
    backgroundColor: '#ffffff',
    zIndex: 1,
  },
  titulo: {
    fontSize: '1.1rem',
    fontWeight: '700',
    color: '#111111',
  },
  cuerpo: {
    padding: '22px 24px',
  },
  footer: {
    padding: '14px 24px',
    borderTop: '1px solid #eeeeee',
    display: 'flex',
    gap: '10px',
    justifyContent: 'flex-end',
  },
  grupo: {
    marginBottom: '15px',
  },
  dosColumnas: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '14px',
    marginBottom: '15px',
  },
  label: {
    display: 'block',
    fontWeight: '600',
    fontSize: '0.84rem',
    color: '#444444',
    marginBottom: '5px',
  },
  labelAyuda: {
    fontWeight: '400',
    color: '#aaaaaa',
    fontSize: '0.77rem',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '6px',
    border: '1px solid #dcdcdc',
    fontSize: '0.9rem',
    fontFamily: "'Montserrat', sans-serif",
    boxSizing: 'border-box',
    outline: 'none',
  },
  inputError: {
    border: '1px solid #cc2200',
  },
  textarea: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '6px',
    border: '1px solid #dcdcdc',
    fontSize: '0.9rem',
    fontFamily: "'Montserrat', sans-serif",
    boxSizing: 'border-box',
    outline: 'none',
    resize: 'vertical',
    minHeight: '88px',
  },
  select: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '6px',
    border: '1px solid #dcdcdc',
    fontSize: '0.9rem',
    fontFamily: "'Montserrat', sans-serif",
    boxSizing: 'border-box',
    outline: 'none',
    backgroundColor: '#ffffff',
    cursor: 'pointer',
  },
  mensajeError: {
    color: '#cc2200',
    fontSize: '0.77rem',
    marginTop: '3px',
    fontWeight: '500',
  },
  infoPasado: {
    backgroundColor: '#f0f7ff',
    border: '1px solid #b3d4f5',
    borderRadius: '6px',
    padding: '9px 13px',
    fontSize: '0.8rem',
    color: '#1565c0',
    marginBottom: '14px',
  },
  tabsImagen: {
    display: 'flex',
    gap: '8px',
    marginBottom: '10px',
  },
  tabBtn: {
    padding: '6px 13px',
    borderRadius: '5px',
    border: '1px solid #dcdcdc',
    backgroundColor: '#ffffff',
    color: '#555555',
    fontSize: '0.78rem',
    fontWeight: '600',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
  },
  tabBtnActivo: {
    border: '1px solid #ff5117',
    backgroundColor: '#ff5117',
    color: '#ffffff',
  },
  previewImagen: {
    marginTop: '8px',
    width: '100%',
    height: '110px',
    objectFit: 'cover',
    borderRadius: '6px',
    border: '1px solid #eeeeee',
    display: 'block',
  },
  inputArchivo: {
    width: '100%',
    padding: '8px',
    borderRadius: '6px',
    border: '1px dashed #dcdcdc',
    fontSize: '0.85rem',
    fontFamily: "'Montserrat', sans-serif",
    cursor: 'pointer',
    backgroundColor: '#fafafa',
  },
  btnCancelar: {
    padding: '10px 22px',
    background: '#f0f0f0',
    color: '#333333',
    border: 'none',
    borderRadius: '6px',
    fontSize: '0.88rem',
    fontWeight: '600',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
  },
  btnGuardar: {
    padding: '10px 22px',
    background: '#ff5117',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '0.87rem',
    fontWeight: '700',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
  },
};

export default styles;
